#!/usr/bin/env ruby

require 'active_support/core_ext/hash/reverse_merge'

def dasherizes(list)
  # edit -c
  list2 = []
  list.each do |item|
    list2 << item.tr('_+', '-')
  end
end

def hi
  puts 'hello world'
end


# step (notice you can't see many lines!)
dasherizes(['hello+world', 'use_the_force'])

# next (step over, don't enter method)
hi

# Make a big hash to show the limited display
hash = 50.times.each_with_object({}) do |i, h|
  h[i] = "*" * i
end
# show hash

# help (show the awesome help)

# demo pry-doc (? and $ "foo".length)

# demo pry-doc (? and $ hash.reverse_merge)

# cd hash and look around

puts 'Done!'
